# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-02 06:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20170327_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecomments',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='userask',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='userfavorite',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='add_time',
        ),
        migrations.AddField(
            model_name='coursecomments',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='coursecomments',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='userask',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='userask',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='\u540d\u79f0'),
        ),
    ]
