# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-10 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='imageFile',
            field=models.ImageField(default='', upload_to='/upload/%Y%m', verbose_name='\u4e5f\u662f\u5c01\u9762\u56fe'),
        ),
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('cj', '\u521d\u7ea7'), ('zj', '\u4e2d\u7ea7'), ('gj', '\u9ad8\u7ea7')], max_length=2, verbose_name='\u8bfe\u7a0b\u96be\u5ea6'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_name', to='courses.Course', verbose_name='\u8bfe\u7a0b'),
        ),
    ]
