# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-26 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170410_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('wlb', '\u7f51\u7edc\u73ed'), ('spb', '\u89c6\u9891\u73ed'), ('msb', '\u9762\u6388\u73ed')], default='', max_length=5, verbose_name='\u8bfe\u7a0b\u7c7b\u578b'),
        ),
    ]
