# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-02 06:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20170426_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='courseresource',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='video',
            name='add_time',
        ),
        migrations.AddField(
            model_name='course',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='courseresource',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='video',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='resource_link',
            field=models.FileField(default='', upload_to='/upload/%Y%m', verbose_name='\u8d44\u6e90\u6587\u4ef6'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_link',
            field=models.FileField(default='', upload_to='/upload/%Y%m', verbose_name='\u89c6\u9891\u5730\u5740'),
        ),
    ]
