# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-26 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_profile', models.TextField(verbose_name='\u516c\u53f8\u7b80\u4ecb')),
                ('teachers', models.TextField(verbose_name='\u5e08\u8d44\u4ecb\u7ecd')),
                ('achievement', models.TextField(verbose_name='\u57f9\u8bad\u6210\u5c31')),
                ('course_description', models.TextField(verbose_name='\u8bfe\u7a0b\u4ecb\u7ecd')),
                ('course_type', models.TextField(verbose_name='\u8bfe\u7a0b\u7c7b\u578b')),
                ('course_content', models.TextField(verbose_name='\u8bfe\u7a0b\u5185\u5bb9')),
                ('main_course', models.TextField(verbose_name='\u4e3b\u8981\u8bfe\u7a0b')),
            ],
            options={
                'verbose_name': '\u7cfb\u7edf\u4fe1\u606f',
                'verbose_name_plural': '\u7cfb\u7edf\u4fe1\u606f',
            },
        ),
    ]
