# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-26 07:21
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': '\u5173\u4e8e\u6211\u4eec', 'verbose_name_plural': '\u5173\u4e8e\u6211\u4eec'},
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='achievement',
            field=tinymce.models.HTMLField(verbose_name='\u57f9\u8bad\u6210\u5c31'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='company_profile',
            field=tinymce.models.HTMLField(verbose_name='\u516c\u53f8\u7b80\u4ecb'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='course_content',
            field=tinymce.models.HTMLField(verbose_name='\u8bfe\u7a0b\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='course_description',
            field=tinymce.models.HTMLField(verbose_name='\u8bfe\u7a0b\u4ecb\u7ecd'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='course_type',
            field=tinymce.models.HTMLField(verbose_name='\u8bfe\u7a0b\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='main_course',
            field=tinymce.models.HTMLField(verbose_name='\u4e3b\u8981\u8bfe\u7a0b'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='teachers',
            field=tinymce.models.HTMLField(verbose_name='\u5e08\u8d44\u4ecb\u7ecd'),
        ),
    ]
